sudo: required
services:
  - docker

before_install:
  - docker build -t react_client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react_client npm test

after_success:
  - docker build -t bartekbulat/multi-client ./client
  - docker build -t bartekbulat/multi-nginx ./nginx
  - docker build -t bartekbulat/multi-server ./server
  - docker build -t bartekbulat/multi-worker ./worker
  - docker login -u "$DOCKER_ID" --password-stdin <<<"$DOCKER_PASSWORD"
  - docker push bartekbulat/multi-client
  - docker push bartekbulat/multi-nginx
  - docker push bartekbulat/multi-server
  - docker push bartekbulat/multi-worker
